on:
  push:
    workflow_dispatch:
    branches: [ main, master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t main .   
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{ secrets.TOKEN }} 
          -e SECRET=${{ secrets.SECRET }} 
          -e MASTERNAME=${{ secrets.MASTER_NAME }} 
          main
      
