name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: cd app && docker build -t main .
      - name: push
        run: >
          # echo {{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u jimbrig --password-stdin && \
          docker login ghcr.io && docker tag main ghcr.io/jimbrig/jimsghstars:latest && docker push ghcr.io/jimbrig/jimsghstars:latest
      - name: execute
        run: >
          docker run 
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} 
          -e TOKEN=${{ secrets.TOKEN }} 
          -e SECRET=${{ secrets.SECRET }} 
          -e MASTERNAME=${{ secrets.MASTER_NAME }} 
          main
      
